name: Push workflow

on: push

jobs:
  Trivy-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Trivy
        run: |
          docker run -v $(pwd):/work -t aquasec/trivy:0.28.0 fs --format sarif --output results.sarif .
      - name: Debug
        run: |
          cat results.sarif
      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: 'debug-trivy-results.sarif'
