name: Push workflow

on: push

jobs:
  Trivy-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Test env vars
        run: |
          echo "MY_VAR=myvalue" >> $GITHUB_ENV
      - name: Echo env var
        run: |
          echo ${{ env.MY_VAR }}
      # - name: Repository Dispatch
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     token: ${{ secrets.CFARREND_GITHUB_TOKEN }}
      #     event-type: on-demand-build
      #     client-payload: '{ "repositories" : ["github-actions-workflows", ""] }'
      # - name: Checkout code
      #   uses: actions/checkout@v3
      # - name: Trivy
      #   run: |
      #     docker run -v $(pwd):/work -t aquasec/trivy:0.28.0 fs --format sarif --output /work/results.sarif .
      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     category: trivy
      #     sarif_file: 'results.sarif'
