name: Trivy workflow

on:
  repository_dispatch:
    types: on-demand-build

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  Trivy-Scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: ${{ github.event.client_payload.repositories }}
        # include:
        #   repository: ${{ github.event.client_payload.repositories }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
