name: Trivy workflow

on:
  repository_dispatch:
    types: on-demand-build

jobs:
  Trivy-Scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          repository: ${{ github.event.client_payload.repositories }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
